### ISSUE TITLE
Sleep LoRa module between use

### ISSUE THREAD

**Issue by FokkeZB** [TheThingsNetwork/arduino-device-lib#115]

**Comment by amkuipers** [comment]
For a node that will delay for an hour, it would be nice to have a method to go to sleep for an hour and have a `onWakeup() `method called after that hour. 
That method then should be capable to read a sensor, transmit it, and optionally continue to sleep. the `onWakeup()` could `return true `so it stays awake, and `return false` would again do a sleep for the specified amount of time.

**Comment by johanstokking** [comment]
@amkuipers definitely agreed. This is issue however addresses bringing the LoRa module itself to sleep, not the Arduino application code.
