### ISSUE TITLE
Not correct bytes received

### ISSUE THREAD

**Issue by Nicolasdejean** [TheThingsNetwork/arduino-device-lib#118]
When I send a byte of value `11` via the dashboard, I receive a byte of value `17` I get this ouput: 
```
 Sending: mac tx uncnf 2 00
Airtime added: 0.06 s
Total airtime: 0.29 s
Successful transmission. Received 1 bytes
-- MESSAGE
Received 1 bytes on port 1: 17
```
I don't know if I am the only one with this ouput...

**Comment by Nicolasdejean** [comment]
And the port from the downlink isn't the same as the port from the uplink.

**Comment by johanstokking** [comment]
What you send from the dashboard is hex `0x11`, which is `17` decimal so that's fine.

The uplink and downlink port are separate.
