### ISSUE TITLE
2.1 breaks non-AVR compatibility

### ISSUE THREAD

**Issue by Bonobo79** [TheThingsNetwork/arduino-device-lib#182]
The latest update adds in the PinChangeInterrupt library which completely breaks everything non-AVR. My suggestion would be to disable that dependency upon using a non-AVR chip, like a SAMD21, used in the Arduino Zero. I honestly don't see a valid reason to use it for simple serial communication.

**Comment by sabas1080** [comment]
Same problem with ESP8266

**Comment by johanstokking** [comment]
Now definitely closed by #186

**Comment by sabas1080** [comment]
I'm going to test, thanks
