### ISSUE TITLE
Move TheThingsNode to another library

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/arduino-device-lib#185]
Pin interrupt dependencies limit the number of boards. This library is just serial interfacing and should be compatible with all Arduino boards.

**Comment by svenhaitjema** [comment]
Grappig toeval, hier wilde ik je gisteren over gaan mailen :)

Groetjes Sven

Op 18 feb. 2017 11:09 a.m. schreef "Johan Stokking" <
notifications@github.com>:
