### ISSUE TITLE
Add delay after saveState()

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/arduino-device-lib#209]
https://github.com/TheThingsNetwork/arduino-device-lib/blob/master/src/TheThingsNetwork.cpp#L494

+ `delay(1000);`

**Comment by jpmeijers** [comment]
Isn't this problem because we do not wait for an "ok" after sending "mac save"?
https://github.com/TheThingsNetwork/arduino-device-lib/blob/master/src/TheThingsNetwork.cpp#L430

**Comment by jpmeijers** [comment]
See https://github.com/jpmeijers/RN2483-Arduino-Library/blob/master/src/rn2xx3.cpp#L307
There I wait with a 60s timeout for the save to happen.

**Comment by jpmeijers** [comment]
Fixed by https://github.com/TheThingsNetwork/arduino-device-lib/pull/211
