### ISSUE TITLE
set correct duty-cycle(s) after join

### ISSUE THREAD

**Issue by tftelkamp** [TheThingsNetwork/arduino-device-lib#21]
From the RN2483 documentation:

"The default settings consider only the three default channels (0-2), and their default duty cycle is 0.33%. If a new channel is created either by the server or by the user, all the channels (including the default ones) must be updated by the user in terms of duty cycle to comply with the ETSI regulations."

In multiple ways this is not a good implementation, but we have to work with it.

After a join, the arduino-library should set the correct duty cycles.

First, count the number of active channels (#totalchan) using the "mac get ch status" command for channels 0-15.

The duty cycle value (dcycle) to be configured on a channel is defined as: <dutyCycle> = (100/X) – 1

X is the intended duty cycle in percent. For EU we need to configure a band total duty cycle of 1%, so per channel a duty cycle of 1/#totalchan.

For each active channel, set the dcycle value to (100/(1/#totalchan)) – 1, using: 

mac set ch dcycle <channelID> <dutyCycle>

Simplified formula: (100*#totalchan)-1 for a band duty-cyle of 1%.

**Comment by tftelkamp** [comment]
Apologies, my formula was wrong! Updated the initial comment.

**Comment by Nicolasdejean** [comment]
closed by #63
