### ISSUE TITLE
Need to configure rx2 settings and extra channels  for ABP

### ISSUE THREAD

**Issue by tftelkamp** [TheThingsNetwork/arduino-device-lib#22]
Set RX2 data rate to SF9:

"mac set rx2 3 869525000"

For these frequencies, configure channels 3-7:

867100000
867300000
867500000
867700000
867900000

mac set ch freq <channelID> <frequency>
mac set ch drrange <channelID> 0 5
mac set ch status <channel ID> on

The for all channels, 0-7, set:

mac set ch dcycle <channelID> 799

Additionally, change the drrange for channel 1 (868.3 Mhz) to include SF7BW250:

mac set ch drrange 1 0 6

**Comment by johanstokking** [comment]
How specific is this for EU 868 frequency plan?

Proposed implementation in #31, but that looks like a lot of magic numbers to me that may be very specific to a frequency plan.

**Comment by tftelkamp** [comment]
Indeed, this is specific to the TTN EU868 plan. It should only be applied on the RN2483.

**Comment by Nicolasdejean** [comment]
closed by #63

**Comment by Nicolasdejean** [comment]
Should we close #22 and #21 by #63 ?

**Comment by Nicolasdejean** [comment]
closed by #63
