### ISSUE TITLE
API: Add poll() as alias for sendBytes()

### ISSUE THREAD

**Issue by FokkeZB** [TheThingsNetwork/arduino-device-lib#27]
Messages can only be received in response to a message send.

To make this less confusing we should add a method `poll([port])` which simply calls `sendBytes()` with a single byte. The developer won't have to construct a byte array and think about what to send if all he cares for is receive.

```c
ttn.poll();
```

**Comment by tftelkamp** [comment]
You should be able to do this without sending a byte, just an empty payload.

**Comment by johanstokking** [comment]
@tftelkamp it doesn't unfortunately. It's gonna be one byte.

**Comment by tftelkamp** [comment]
Yeah, I noticed. Let's file an issue with microchip, it just doesn't make sense to send data if you only want downlink.
