### ISSUE TITLE
ISM_2400_3CH_DRAFT2 support?

### ISSUE THREAD

**Issue by mo8Zomo0** [TheThingsNetwork/arduino-device-lib#283]
Is there any device supported which would support ISM2400? 
The library does not seem to support it, so possibly no?
And if there are devices out there, are there plans to support it in this lib?

**Comment by jpmeijers** [comment]
This library is meant for The Things Node and The Things Uno, which both use the RN2483 or RN2903 modules. These modules are 433MHz/868MHz and 915MHz respectively. They do not support the 2.4GHz band. Therefore ISM_2400 will never be supported.

It seems like you are rather looking for a generic LoRaWAN library. Maybe check out:
* https://github.com/mcci-catena/arduino-lorawan
* https://github.com/LacunaSpace/basicmac
* https://github.com/Lora-net/LoRaMac-node
* https://github.com/beegee-tokyo/SX126x-Arduino

Also have a look at the RN2xx3 firmware repo:
https://github.com/MicrochipTech/RN2xx3_LORAWAN_FIRMWARE
