### ISSUE TITLE
Initialize library for specific frequency plan

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/arduino-device-lib#32]
Issues #21 and #22 are frequency plan specific, but the library does not accommodate for frequency plans yet. Instead, it only checks the RN module. We cannot assume that RN2483 is used in EU868.

We should define frequency plans, e.g. `#define TTN_EU868 1`, and initialize the library with this frequency plan. Instead of checking the RN module, it should assert that the RN module matches the frequency plan (e.g. `TTN_EU868` needs `RN2483`), and based on the frequency plan, configure the channels and duty cycle.

**Comment by FokkeZB** [comment]
Closed by #63
