### ISSUE TITLE
Support (max) number of retries for confirm

### ISSUE THREAD

**Issue by FokkeZB** [TheThingsNetwork/arduino-device-lib#51]
* [ ] Keep listening in `sendBytes()` because with confirm it will keep trying
* [ ] Use `mac set retx TTN_RETX` to set max retries (should be constant in header)

**Comment by johanstokking** [comment]
Keep listening in `sendBytes()`, no 10 seconds timeout in `readLine()`.

Set `TTN_RETX` to 7 (default for RN module)

**Comment by Nicolasdejean** [comment]
@johanstokking @FokkeZB Where do I use ``` mac set retx ```, in sendBytes ?

**Comment by FokkeZB** [comment]
Closed by #91
