### ISSUE TITLE
Node: Add getPayload

### ISSUE THREAD

**Issue by FokkeZB** [TheThingsNetwork/arduino-device-lib#74]
Which should return a byte array with all data as small as possible.

**Comment by FokkeZB** [comment]
Not sure if this makes much sense to have in the lib instead of just providing an example. @johanstokking?

**Comment by johanstokking** [comment]
I think it's good to have it in the library, just to make it very easy. Also, consider using protobufs for this, that makes the example even stronger.

**Comment by FokkeZB** [comment]
I'll wait for @Nicolasdejean to #78 and do that then.
