### ISSUE TITLE
Design generic Measurement protobuf

### ISSUE THREAD

**Issue by johanstokking** [TheThingsNetwork/arduino-device-lib#79]
E.g.:

```
message Measurement {
   optional float temperature = 100;
   optional float humidity = 101;

   repeated uint32 analog_readings = 110;
}
```

**Comment by FokkeZB** [comment]
I couldn't sleep tonight and had an idea for a Message class that could contain any number of values, encoded in minimal bytes based on max range and min precision.

https://github.com/TheThingsNetwork/arduino-device-lib/wiki/Proposal:-Message-Class

**Comment by johanstokking** [comment]
@FokkeZB this is what protobufs will be for 👍

This allows for a generic, reusable `Message` that contains many optional fields and arrays for custom data. The device sets the fields it needs and the protobuf marshaler only puts the used values in the buffer with a tiny header. It also supports variable length integers.

I have a demo ready shortly.

**Comment by johanstokking** [comment]
@FokkeZB see some example code in #81. The file https://github.com/johanstokking/ttn-protobuf-demo/blob/master/api/measurement.proto contains `required` fields, but they will be `optional` and a long list of things we can send. We can also send variable length arrays of analog readings, but putting values in the right fields helps upstream.

**Comment by FokkeZB** [comment]
wow, I did quite some C coding lately, but that puzzles me 😛

**Comment by FokkeZB** [comment]
Done by #108
